baseURL = "/"
languageCode = "es"
title = "La Sobremesa"
defaultContentLanguage = "es"
taxonomies = []

[languages]
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 1
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

[markup.goldmark.renderer]
  unsafe= true