module.exports = {
  purge: {
    enabled: process.env.HUGO_ENVIRONMENT === "production",
    content: ["./layouts/**/*.html"],
    options: {
      safelist: [
        "bg-tools-sm-es",
        "md:bg-tools-lg-es",
        "bg-spaces-sm-es",
        "md:bg-spaces-lg-es",
        "bg-accompaniment-sm-es",
        "md:bg-accompaniment-lg-es",
        "bg-tools-sm-en",
        "md:bg-tools-lg-en",
        "bg-spaces-sm-en",
        "md:bg-spaces-lg-en",
        "bg-accompaniment-sm-en",
        "md:bg-accompaniment-lg-en",
        "-left-full",
        "left-0",
        "modal-wrapper",
        "is-open",
        "hidden",
        "bg-black",
        "text-white",
        "text-chocolate",
        "hidden"
      ],
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    minWidth: {
      165: "165px",
      380: "380px",
    },
    extend: {
      inset: {
        18: "4.5rem",
        "-18": "-4.5rem",
      },
      lineHeight: {
        "extra-tight": "0.75",
      },
      colors: {
        chocolate: "#1f1b18",
        "darmouth-green": "#007540",
        "fire-opal": "#ea5745",
        "gold-metallic": "#d8b400",
        linen: "#fff4e7",
        blue: "#0036f6",
        "maximum-green": "#618D3F",
        "pine-green": "#007266",
        "fern-green": "#497B56",
        "office-green": "#1D7F32",
        "office-green-2": "#1B7302",
        "pakistan-green": "#154001",
        "dark-spring-green": "#00763F",
        pear: "#C5EB46",
        lime: "#D0F646",
        "lime-2": "#B9DE46",
        "lavender-pink": "#EEABC4",
        "amaranth-pink": "#DF9CB5",
        onyx: "#414042",
        vanilla: "#FEF2B7",
        alabaster: "#F2F0E6",
        "alabaster-2": "#E9E7DD",
      },
      fontFamily: {
        "beth-ellen": ['"Beth Ellen"', "cursive"],
        martin: ["MARTIN", "sans-serif"],
        "source-sans-pro": ['"Source Sans Pro"', "sans-serif"],
        "source-serif-pro": ['"Source Serif Pro"', "serif"],
        "open-sans": ['"Open Sans"', "sans-serif"],
        ramona: ["Ramona", "sans-serif"],
      },
      backgroundImage: {
        "tools-sm-es": "url('/images/tools-sm-es.svg')",
        "tools-lg-es": "url('/images/tools-lg-es.svg')",
        "spaces-sm-es": "url('/images/spaces-sm-es.svg')",
        "spaces-lg-es": "url('/images/spaces-lg-es.svg')",
        "accompaniment-sm-es": "url('/images/accompaniment-sm-es.svg')",
        "accompaniment-lg-es": "url('/images/accompaniment-lg-es.svg')",
        "tools-sm-en": "url('/images/tools-sm-en.svg')",
        "tools-lg-en": "url('/images/tools-lg-en.svg')",
        "spaces-sm-en": "url('/images/spaces-sm-en.svg')",
        "spaces-lg-en": "url('/images/spaces-lg-en.svg')",
        "accompaniment-sm-en": "url('/images/accompaniment-sm-en.svg')",
        "accompaniment-lg-en": "url('/images/accompaniment-lg-en.svg')",
        "cursos-banner-1": "url('/images/cursos/cursos-banner-1.jpg')",
        "cursos-banner-2": "url('/images/cursos/cursos-banner-2.jpg')",
        "cursos-banner-3": "url('/images/cursos/cursos-banner-3.jpg')",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/line-clamp"),
  ],
  corePlugins: {
    container: false,
  },
};
