backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: accompaniments-en
    label: Experiences (English)
    folder: content/en/acompanamiento
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Client"
        name: "client"
        widget: "string"
        required: true
      - label: "Logo"
        name: "logo"
        widget: "image"
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Role"
        name: "role"
        widget: "string"
        required: true
      - label: "Website"
        name: "web"
        widget: "string"
        required: true
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Experience"
        name: "body"
        widget: "markdown"
  - name: accompaniments-es
    label: Experiencias (Español)
    folder: content/es/acompanamiento
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Cliente"
        name: "client"
        widget: "string"
        required: true
      - label: "Logo"
        name: "logo"
        widget: "image"
      - label: "Nombre"
        name: "name"
        widget: "string"
        required: true
      - label: "Rol"
        name: "role"
        widget: "string"
        required: true
      - label: "Sitio web"
        name: "web"
        widget: "string"
        required: true
      - label: "Borrador"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Experiencia"
        name: "body"
        widget: "markdown"
  - name: tools-en
    label: Tools (English)
    folder: content/en/herramientas
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Type"
        name: "genre"
        widget: "select"
        options:
          - { label: "Podcast", value: "podcast" }
          - { label: "Video", value: "video" }
          - { label: "Website", value: "website" }
          - { label: "Guide", value: "guide" }
          - { label: "Book", value: "book" }
          - { label: "Tool", value: "tool" }
          - { label: "Report", value: "report" }
          - { label: "Blog post", value: "blogpost" }
          - { label: "Methodology", value: "methodology" }
          - { label: "Template", value: "template" }
          - { label: "Repository", value: "repository" }
        required: false
      - label: "Topic"
        name: "topic"
        widget: "select"
        options:
          - { label: "Misión", value: "mision" }
          - { label: "Visión", value: "vision" }
          - { label: "Theory of change", value: "theory of change" }
          - { label: "Strategies", value: "strategies" }
          - { label: "Annual Retreats", value: "annual retreats" }
          - { label: "Planning", value: "planning" }
          - { label: "Project design", value: "project design" }
          - { label: "Networking and Organization Building", value: "networking and organization building" }
          - { label: "Financial sustainability", value: "financial sustainability" }
          - { label: "Monitoring, Evaluation and Learning", value: "monitoring, evaluation and learning" }
          - { label: "Transitions", value: "transitions" }
          - { label: "New leaderships", value: "new leaderships" }
          - { label: "Healthy team", value: "healthy team" }
        required: false
      - label: "Language"
        name: "language"
        widget: "select"
        options:
          - { label: "Spanish", value: "spanish" }
          - { label: "English", value: "english" }
          - { label: "Portuguese", value: "portuguese" }
        required: false
      - label: "For whom?"
        name: "for_whom"
        widget: "select"
        options:
          - { label: "Organizations", value: "organizations" }
          - { label: "Leaders", value: "leaders" }
          - { label: "Networks", value: "networks" }
          - { label: "Donors", value: "donors" }
        required: false
      - label: "Recommended tool"
        name: "recommended"
        widget: "boolean"
        default: false
      - label: "Clip"
        name: "clip"
        widget: "file"
        media_library:
          allow_multiple: false
      - label: "URL"
        name: "resource_url"
        widget: "string"
        required: true
      - label: "Creator"
        name: "creator"
        widget: "string"
        required: true
      - label: "Target"
        name: "target"
        widget: "string"
        required: true
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Description"
        name: "body"
        widget: "markdown"
  - name: tools-es
    label: Herramientas (Español)
    folder: content/es/herramientas
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Tipo"
        name: "genre"
        widget: "select"
        options:
          - { label: "Podcast", value: "podcast" }
          - { label: "Vídeo", value: "video" }
          - { label: "Sitio web", value: "website" }
          - { label: "Guía", value: "guide" }
          - { label: "Libro", value: "book" }
          - { label: "Herramienta", value: "tool" }
          - { label: "Reporte", value: "report" }
          - { label: "Blog post", value: "blogpost" }
          - { label: "Metodología", value: "methodology" }
          - { label: "Plantilla", value: "template" }
          - { label: "Repositorio", value: "repository" }
        required: false
      - label: "Tema"
        name: "topic"
        widget: "select"
        options:
          - { label: "Misión", value: "mision" }
          - { label: "Visión", value: "vision" }
          - { label: "Teoría de Cambio", value: "theory of change" }
          - { label: "Estrategias", value: "strategies" }
          - { label: "Retiros Anuales", value: "annual retreats" }
          - { label: "Planeación", value: "planning" }
          - { label: "Diseño de proyectos", value: "project design" }
          - { label: "Creación de redes y organizaciones", value: "networking and organization building" }
          - { label: "Sostenibilidad financiera", value: "financial sustainability" }
          - { label: "Monitoreo, Evaluación y Aprendizaje", value: "monitoring, evaluation and learning" }
          - { label: "Transiciones", value: "transitions" }
          - { label: "Nuevos liderazgos", value: "new leaderships" }
          - { label: "Equipo sano", value: "healthy team" }
        required: false
      - label: "Language"
        name: "language"
        widget: "select"
        options:
          - { label: "Español", value: "spanish" }
          - { label: "Inglés", value: "english" }
          - { label: "Portugués", value: "portuguese" }
        required: false
      - label: "Para quién?"
        name: "for_whom"
        widget: "select"
        options:
          - { label: "Organizaciones", value: "organizations" }
          - { label: "Líderes", value: "leaders" }
          - { label: "Redes", value: "networks" }
          - { label: "Donantes", value: "donors" }
        required: false
      - label: "Herramienta recomendada"
        name: "recommended"
        widget: "boolean"
        default: false
      - label: "Clip"
        name: "clip"
        widget: "file"
        media_library:
          allow_multiple: false
      - label: "URL"
        name: "resource_url"
        widget: "string"
        required: true
      - label: "Creador"
        name: "creator"
        widget: "string"
        required: true
      - label: "Objetivo"
        name: "target"
        widget: "string"
        required: true
      - label: "Fecha de actualización"
        name: "lastmod"
        widget: "datetime"
      - label: "Borrador"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Descripción"
        name: "body"
        widget: "markdown"

