backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: accompaniments-en
    label: Experiences (English)
    folder: content/en/acompanamiento
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Client"
        name: "client"
        widget: "string"
        required: true
      - label: "Logo"
        name: "logo"
        widget: "image"
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Role"
        name: "role"
        widget: "string"
        required: true
      - label: "Website"
        name: "web"
        widget: "string"
        required: true
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Experience"
        name: "body"
        widget: "markdown"
  - name: accompaniments-es
    label: Experiencias (Español)
    folder: content/es/acompanamiento
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Cliente"
        name: "client"
        widget: "string"
        required: true
      - label: "Logo"
        name: "logo"
        widget: "image"
      - label: "Nombre"
        name: "name"
        widget: "string"
        required: true
      - label: "Rol"
        name: "role"
        widget: "string"
        required: true
      - label: "Sitio web"
        name: "web"
        widget: "string"
        required: true
      - label: "Borrador"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Experiencia"
        name: "body"
        widget: "markdown"
  - name: tools-en
    label: Tools (English)
    folder: content/en/herramientas
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Type"
        name: "genre"
        widget: "select"
        options:
          - { label: "Podcast", value: "podcast" }
          - { label: "Video", value: "video" }
          - { label: "Website", value: "website" }
          - { label: "Guide", value: "guide" }
          - { label: "Book", value: "book" }
          - { label: "Tool", value: "tool" }
          - { label: "Report", value: "report" }
          - { label: "Blog post", value: "blogpost" }
          - { label: "Methodology", value: "methodology" }
          - { label: "Template", value: "template" }
          - { label: "Repository", value: "repository" }
        required: true
      - label: "Thematics"
        name: "topic"
        widget: "select"
        options:
          - { label: "Sustainability", value: "sustainability" }
          - { label: "Governance", value: "governance" }
          - { label: "Administration", value: "administration" }
          - { label: "Leadership", value: "leadership" }
          - { label: "Team", value: "team" }
          - { label: "Design", value: "design" }
          - { label: "Monitoring and evaluation", value: "monitoring" }
          - { label: "Annual Plan", value: "plan" }
          - { label: "Organizational strategy", value: "strategy" }
        required: true
      - label: "Clip"
        name: "clip"
        widget: "file"
        media_library:
          allow_multiple: false
      - label: "URL"
        name: "resource_url"
        widget: "string"
        required: true
      - label: "Creator"
        name: "creator"
        widget: "string"
        required: true
      - label: "Target"
        name: "target"
        widget: "string"
        required: true
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Description"
        name: "body"
        widget: "markdown"
  - name: tools-es
    label: Herramientas (Español)
    folder: content/es/herramientas
    create: true
    slug: "{{slug}}"
    filter: {field: "entry", value: true}
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Tipo"
        name: "genre"
        widget: "select"
        options:
          - { label: "Podcast", value: "podcast" }
          - { label: "Vídeo", value: "video" }
          - { label: "Sitio web", value: "website" }
          - { label: "Guía", value: "guide" }
          - { label: "Libro", value: "book" }
          - { label: "Herramienta", value: "tool" }
          - { label: "Reporte", value: "report" }
          - { label: "Blog post", value: "blogpost" }
          - { label: "Metodología", value: "methodology" }
          - { label: "Plantilla", value: "template" }
          - { label: "Repositorio", value: "repository" }
        required: true
      - label: "Temáticas"
        name: "topic"
        widget: "select"
        options:
          - { label: "Sostenibilidad", value: "sustainability" }
          - { label: "Gobernanza", value: "governance" }
          - { label: "Administración", value: "administration" }
          - { label: "Liderazgo", value: "leadership" }
          - { label: "Equipo", value: "team" }
          - { label: "Diseño", value: "design" }
          - { label: "Monitoreo y evaluación", value: "monitoring" }
          - { label: "Plan Anual", value: "plan" }
          - { label: "Estrategia organizacional", value: "strategy" }
        required: true
      - label: "Clip"
        name: "clip"
        widget: "file"
        media_library:
          allow_multiple: false
      - label: "URL"
        name: "resource_url"
        widget: "string"
        required: true
      - label: "Creador"
        name: "creator"
        widget: "string"
        required: true
      - label: "Objetivo"
        name: "target"
        widget: "string"
        required: true
      - label: "Fecha de actualización"
        name: "lastmod"
        widget: "datetime"
      - label: "Borrador"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Entry"
        name: "entry"
        widget: "hidden"
        default: true
      - label: "Descripción"
        name: "body"
        widget: "markdown"

