baseURL = "/"
languageCode = "es"
title = "La Sobremesa"
defaultContentLanguage = "es"
taxonomies = []

[params]
  image = "https://lasobremesa.co/images/Card_V2_CursoSostenibilidad-04.png"
  twitterHandle = "@LaSobremesa_co"

[languages]
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 1
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2
